{% set name = "xmldiff" %}
{% set version = "3.0" %}
{% set sha256 = "380ec4d05cef33f5b706cf789abcc848d27730d67e02dc0b4f1107e16ce9aaad" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/dc/f5/c2200adb02cb64e5db05bd28fff1032d05d33ac632e3c781142a7aa61bcf/xmldiff-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - xmldiff = xmldiff.main:diff_command
    - xmlpatch = xmldiff.main:patch_command

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - lxml
    - setuptools
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - xmldiff
  commands:
    - xmldiff -h
    - xmlpatch -h

about:
  home: https://github.com/Shoobx/xmldiff
  summary: 'Creates diffs of XML files'
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  description: |
    xmldiff is a library and a command-line utility for making diffs out of XML
  doc_url: https://xmldiff.readthedocs.io/
  dev_url: https://github.com/Shoobx/xmldiff

extra:
  recipe-maintainers:
    - bernt-matthias
